---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install a list of packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ installed_packages }}"
  become: yes
