---
- name: Add user to sudo for passwordless ansible work 
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ ansible_user_id }}'
    line: '{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  become: true
