---
- hosts: all
  vars:
    ansible_become: yes
    ansible_become_method: sudo
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
